export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";

export const LOGIN_USER = `LOGIN_USER`;
export const LOGIN_SUCCESS = `LOGIN_SUCCESS`;
export const LOGIN_FAIL = `LOGIN_FAIL`;

export const GET_PROFILE = `GET_PROFILE`;
export const GET_PROFILE_SUCCESS = `GET_PROFILE_SUCCESS`;
export const GET_PROFILE_FAIL = `GET_PROFILE_FAIL`;
export const LOGOUT = `LOGOUT`;

export const FETCH_ALL_USERS = ` FETCH_ALL_USERS`;
export const FETCH_ALL_USERS_SUCCESS = `FETCH_ALL_USERS_SUCCESS`;
export const FETCH_ALL_USERS_FAIL = `FETCH_ALL_USERS_FAIL`;

export const SEE_ALL_PREFERENCES = `SEE_ALL_PREFERENCES`;

export const ADD_PREFERENCES = `ADD_PREFERENCES`;
export const ADD_PREFERENCES_SUCCESS = `ADD_PREFERENCES_SUCCESS`;
export const ADD_PREFERENCES_FAIL = `ADD_PREFERENCES_FAIL`;
